name: my-workflow

on:
  push:
    branches:
      - 'master'


jobs:
  testing:
    name: testing
    runs-on: ubuntu-latest
    steps:
      # ...
      - uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v1

      # run any `bun` or `bunx` command
      - run: bun install
      - run: bun test
